defaults:
  - _self_
  - paths: default
  - data: synthetic
  - model: SPACY # SPACY, SPACY_Multi
  - logger: many_loggers # csv, wandb, many_loggers
  - trainer: default
  - experiment: null


checkpoint_path: /your/checkpoint/path
random_seed: 0